import { ArrowLeft } from 'lucide-react';
import { Link } from './Router';

export default function Terms() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <Link href="/" className="inline-flex items-center gap-2 text-[#020CFE] hover:text-[#0108d4] mb-8 transition-colors">
          <ArrowLeft size={20} />
          Back to Home
        </Link>

        <div className="prose prose-lg max-w-none">
          <h1 className="text-4xl lg:text-5xl font-bold text-[#0a0a0a] mb-8">Terms and Conditions</h1>

          <div className="space-y-6 text-gray-700 leading-relaxed text-sm">
            <p className="text-base text-gray-600">
              Last updated: November 10, 2025
            </p>

            <h2 className="text-2xl font-bold text-[#0a0a0a] mt-8">1. GENERAL PROVISIONS</h2>
            <p>
              These Terms and Conditions (hereinafter referred to as the "Terms") govern Your access (hereinafter referred to as "You" or the "Consumer") to and use of the website https://www.zuvu.ai/, as well as the related software, interface, plugins, and server infrastructure (collectively the "Service").
            </p>
            <p>
              The Service is an interactive platform that allows Consumers to select and use various AI models for information search, communication, analytics, text generation, or professional and educational purposes. Requests are processed automatically using artificial intelligence algorithms that analyze the entered information, generate responses based on open and licensed sources, and provide results in the format of a text dialogue.
            </p>
            <p>
              The results of interaction with the chats are of a recommendatory nature and do not guarantee full accuracy or relevance. The Consumer independently evaluates the reliability of the received responses and makes decisions at their own risk.
            </p>
            <p>
              The Service is owned and operated by ZD Pro Inc., a legal entity registered in accordance with the legislation of Republic of Seychelles, with its registered office at Oliaji, Trade Centre -1st Floor, Victoria, Mahe, Republic of Seychelles (hereinafter referred to as the "Company," "We," or "Us").
            </p>
            <p>
              The Company does not participate in communications between Consumers or between Consumers and third-party systems, does not control the content of requests and responses generated by AI models, and is not responsible for the accuracy, legality, or consequences of the use of the provided information. All responsibility for the use of the Service, including compliance with copyright, licensing requirements, and applicable law, lies solely with the Consumer.
            </p>
            <p>
              The use of the Service is carried out by the Consumer at their own risk. The Consumer undertakes not to use the Service to distribute false, illegal, or harmful materials, as well as to attempt unauthorized access to systems or data of other Consumers.
            </p>
            <p>
              We strive to ensure the compliance of the Site's operation with international standards, to guarantee its proper functioning, and to protect consumers' data. By using the Service, You confirm that You have read these Terms and agree to comply with them.
            </p>
            <p>
              In addition to these Terms, interaction with the Service is governed by the Privacy Notice, which explains in detail how We collect, store, and process Your personal data.
            </p>

            <h3 className="text-xl font-bold text-[#0a0a0a] mt-6">1.2. Acceptance of the Terms</h3>
            <p>
              These Terms are considered accepted by You from the moment of creating an Account on the Service, which confirms the fact of Your acquaintance with them and Your consent to their application.
            </p>
            <p>
              Using the Service means Your full and unconditional agreement with these Terms. This confirms that You have carefully read their content, understand their meaning, and undertake to comply with all provisions set forth herein.
            </p>
            <p>
              If You do not agree with any provision of these Terms, You have no right to use the Service, register an Account, or gain access to its functionality.
            </p>

            <h3 className="text-xl font-bold text-[#0a0a0a] mt-6">1.3. Right to use</h3>
            <p>
              The Service is available only to persons who have the legal capacity to enter into legally binding agreements in accordance with the laws of their jurisdiction. The use of the Service is prohibited for persons who have not reached the minimum age established by the legislation of their country, or who do not meet other established legal requirements.
            </p>
            <p>By using the Service, You confirm that:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>You have reached the minimum age required to enter into legally binding agreements in accordance with applicable law;</li>
              <li>the use of the Service in Your jurisdiction is lawful;</li>
              <li>You act on Your own behalf or have the necessary authority to act on behalf of the organization You represent.</li>
            </ul>
            <p>
              The Company reserves the right to deny any Consumer access to the Service if it is determined that the Consumer does not meet the above requirements or violates other provisions of these Terms.
            </p>

            <h2 className="text-2xl font-bold text-[#0a0a0a] mt-8">2. DEFINITION OF TERMS</h2>
            <p>
              This section defines the main terms used in these Terms in order to ensure a clear understanding of the Terms.
            </p>
            <p>
              <strong>Service</strong> – means the website https://www.zuvu.ai/, as well as the related software, including plugins, server infrastructure, and interface that provide Consumers with access to functions for creating, processing, and analyzing Information, integrating with other systems, and receiving related services.
            </p>
            <p>
              <strong>Company or We</strong> – means the legal entity ZD Pro Inc., registered in accordance with the legislation of the Republic of Seychelles, which owns and manages the intellectual property rights to all elements of the Service.
            </p>
            <p>
              <strong>Consumer or You</strong> – means any natural or legal person who gains access to the Service, directly or indirectly uses its functionality, creates an Account, or interacts with the Service in any other permitted way.
            </p>
            <p>
              <strong>Account</strong> – means a unique Consumer profile on the Service, created for identification, access to the personal account, management of Information, configuration of functionality, and obtaining the Service's offerings.
            </p>
            <p>
              <strong>Information</strong> – means any texts, requests, instructions, or other materials that the Consumer enters or creates within the Service.
            </p>
            <p>
              <strong>Pricing plan</strong> – means a set of terms and conditions established by the Company that define the scope, procedure, and specific features of using the Service.
            </p>

            <p className="mt-12 text-base italic">
              For the complete Terms and Conditions document including all sections 3-12, please continue reading below or contact us at contact@zuvu.ai
            </p>

            <div className="mt-12 p-6 bg-gray-50 rounded-xl border border-gray-200">
              <h2 className="text-xl font-semibold text-[#0a0a0a] mb-2">Questions?</h2>
              <p className="text-gray-600">
                For any questions about our Terms of Service, please contact us at{' '}
                <a href="mailto:contact@zuvu.ai" className="text-[#020CFE] hover:underline">
                  contact@zuvu.ai
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
